name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        cd collector
        go mod tidy

    - name: Build
      run: |
        cd collector
        go build ./...

    - name: Run tests
      run: |
        cd collector
        go test ./...
